### ISSUE TITLE
Some clarifications

### ISSUE THREAD

**Issue by forianfinest** [raw-lab/DeGenPrime#3] opened 2023-12-05 13:59 UTC
Hello there,
thank you very much for designing such software, it is very useful!
I just have to understand a couple of things regarding it:
1) is it possible to specify the lenght of foward and reverse primers? I am testing the software with some sequences and I noticed how the foward one is always around 24-25 and the reverse one around 18;
2) in the README, the output is said to be "primers_filename.txt"; however, in my case DeGenPrime told me that "Output details saved to primers_filename.dgp" and the file is actually saved as "filename.dgp"; I am not sure if it is supposed to be like this or not;
3) I did not set the --min_temp flag on my script, assuming it was 50 by default: however, in my output I have something lower, e.g.:
Melting Temperature                   Melting Temperature
            Basic: [44.56]                        Basic: [41.21]
               NN: [40.71]                           NN: [41.00]

I am not sure if I am misinterpreting the output, but I would suppose this should be at least 50.

This is the script I used (with some COXI sequences), let me know if I made any mistake (e..g, if I should add something like an --output flag or similar):

degenprime --amplicon:600 --begin:31 --end:653 --max_primers:10 full_coxi_aligned_l.clust

Best wishes,
Mattia

**Comment by zestywesty** [comment] 2023-12-05 17:33
Hello Mattia,

Our lab has reviewed your issue and I have begun working on some of the problems.

Issue #1: 
I think this feature is an excellent suggestion for primer design and have made changes to implement it.
the program now includes a --max_primer_length:<int> tag and a --min_primer_length:<int> tag.  These tags will enable the user to specific a specific size range for their primers.  The program has been defaulted to have a minimum primer size of 20 and a maximum primer size of 22.  Users can increase the size range of their primers with the tags up to a maximum of 25 bp or a minimum of 18 for their primer, but the program does not allow primers outside this range for practices of good primer design.

Issue #2: 
I'm glad you noticed this.  The string output of the program to the console was written early in this program's development while the README file was updated later and this was an oversight on my part.  I have adjusted the README and console output to appropriately match the file output.

Issue #3:  I am currently investigating this problem so I will keep the issue open until I have it resolved.  In the short term, I hope that the default increase to primer size might raise the average temperatures of the primers suggested by degenprime.  But when I get to the root cause of the problem I will post again to let you know.

Thank you so much for bringing this to my attention.  I will try to finish fixing Issue 3 soon.
~Zesty

**Comment by zestywesty** [comment] 2024-01-14 00:20
Hello Mattia,

I'm sorry for the long reply, I was away for most of the holidays.

Here is my approach to resolving issue 3:

1) I changed the InitializeFromRegion function within the primercalculator.cpp file.  The change now prevents any primer from candidacy should that primer have a Penalty value higher than MAX_PENALTY, a new constant which I added to glohal.h and set to an arbitrary value of 100.
2) I slightly changed the way penalty is calculated in datasequence.cpp.  If a user manually specifies a minimum or maximum temperature for their primer, and a candidate primer is outside their specified range, the program will add 100 to their penalty score (which should ultimately disqualify the primer).  If these tags were not included, the program still assigns penalty depending on how far outside the temperature range the primer falls.

In this approach, if a user does not enter temperature tags and the conserved regions of the MSA are limited, then the program will still show them primers that could still be outside the temperature range, but only if those primers still have the minimum aggregate penalty score.  But if the user entered a temperature tag, then the program interprets this as temperature is extremely important for the primers and will not suggest any primers outside their specified range.

Please let me know if these changes worked for you and if so I will close this issue.

Thank you,

Zesty

**Comment by raw937** [comment] 2024-01-15 18:17
Hello Mattia, 

Can you send us the full length sequences prior to the alignment as well? Also, in your mind what would the perfect primer be? Is it 500 bp or 800 bp? Help us help you?

many thanks,
Rick

**Comment by zestywesty** [comment] 2024-01-16 02:47
Hello Mattia,

I accidentally referenced the global absolute minimum and maximum temperatures in my initial fix on the check istead of the GlobalSettings class variable which stored the changes I made.

I changed the datasequence.cpp file so that it is now referencing the correct variable.

As a quick test, I ran the changes on our SinNombreL.fna file without temp tags and got this for the best primer pair:

./degenprime ../data/SinNombreL.fna

                                 %%%%%%%%%%%                                
                                 % Results %                                
                                 %%%%%%%%%%%                                

      Primer Pair #1       Amplicon Size: [6526]      Temp Diff: [00.08]    
                Forward                               Reverse               
        [GCTTGACCGTCTTTATGCAG]                [CCGAGAACAGAGCAGTAGAG]        
           Basic Information                     Basic Information          
            Range: [116-135]                      Range: [6642-6622]        
           Length: [20]                          Length: [20]               
          Penalty: [01.46]                      Penalty: [00.00]            
          Melting Temperature                   Melting Temperature         
            Basic: [51.78]                        Basic: [53.83]            
               NN: [51.56]                           NN: [51.48]       
               
(I only showed the top result but the top five all had temperatures below 52)
Then adding a minimum temperature of 52:

./degenprime --min_temp:52 ../data/SinNombreL.fna

                                 %%%%%%%%%%%                                
                                 % Results %                                
                                 %%%%%%%%%%%                                

      Primer Pair #1       Amplicon Size: [5445]      Temp Diff: [00.39]    
                Forward                               Reverse               
        [TGCAAGCACTGGCTCACAGA]                [TTCAAGCACGCGCGTTACAC]        
           Basic Information                     Basic Information          
            Range: [784-803]                      Range: [6229-6209]        
           Length: [20]                          Length: [20]               
          Penalty: [02.16]                      Penalty: [00.00]            
          Melting Temperature                   Melting Temperature         
            Basic: [53.83]                        Basic: [53.83]            
               NN: [56.45]                           NN: [56.84]            

Now this and all other results were more than 52.

Did this work for your experiment?

**Comment by forianfinest** [comment] 2024-01-16 08:22
> Hello Mattia,
> 
> Can you send us the full length sequences prior to the alignment as well? Also, in your mind what would the perfect primer be? Is it 500 bp or 800 bp? Help us help you?
> 
> many thanks, Rick

Dear Rick,
thank you very much for your interest! I attach here the not-aligned file.
[toalign.txt](https://github.com/raw-lab/DeGenPrime/files/13947153/toalign.txt)
My idea is to get COXI barcode universal primers for gordiids (Gordiida), the most "famous" group of horsehair worms (phylum Nematomorpha). I noticed in literature that the average size of the barcode for this group is around 600 bp and therefore I guess it would be also fine like this. However, if I could get longer would be better. That being said, I noticed how after some bp there are very few conserved regions (see attached output here) Therefore, I would suppose that getting an amplicon longer than around 800 bp may be tricky.
[output_degen_800.txt](https://github.com/raw-lab/DeGenPrime/files/13947190/output_degen_800.txt)
Generally, the COXI of horsehair worms seems to be around 1532-1542 in lenght.

**Comment by forianfinest** [comment] 2024-01-16 08:24
> Hello Mattia,
> 
> I accidentally referenced the global absolute minimum and maximum temperatures in my initial fix on the check istead of the GlobalSettings class variable which stored the changes I made.
> 
> I changed the datasequence.cpp file so that it is now referencing the correct variable.
> 
> As a quick test, I ran the changes on our SinNombreL.fna file without temp tags and got this for the best primer pair:
> 
> ./degenprime ../data/SinNombreL.fna
> 
> ```
>                              %%%%%%%%%%%                                
>                              % Results %                                
>                              %%%%%%%%%%%                                
> 
>   Primer Pair #1       Amplicon Size: [6526]      Temp Diff: [00.08]    
>             Forward                               Reverse               
>     [GCTTGACCGTCTTTATGCAG]                [CCGAGAACAGAGCAGTAGAG]        
>        Basic Information                     Basic Information          
>         Range: [116-135]                      Range: [6642-6622]        
>        Length: [20]                          Length: [20]               
>       Penalty: [01.46]                      Penalty: [00.00]            
>       Melting Temperature                   Melting Temperature         
>         Basic: [51.78]                        Basic: [53.83]            
>            NN: [51.56]                           NN: [51.48]       
> ```
> 
> (I only showed the top result but the top five all had temperatures below 52) Then adding a minimum temperature of 52:
> 
> ./degenprime --min_temp:52 ../data/SinNombreL.fna
> 
> ```
>                              %%%%%%%%%%%                                
>                              % Results %                                
>                              %%%%%%%%%%%                                
> 
>   Primer Pair #1       Amplicon Size: [5445]      Temp Diff: [00.39]    
>             Forward                               Reverse               
>     [TGCAAGCACTGGCTCACAGA]                [TTCAAGCACGCGCGTTACAC]        
>        Basic Information                     Basic Information          
>         Range: [784-803]                      Range: [6229-6209]        
>        Length: [20]                          Length: [20]               
>       Penalty: [02.16]                      Penalty: [00.00]            
>       Melting Temperature                   Melting Temperature         
>         Basic: [53.83]                        Basic: [53.83]            
>            NN: [56.45]                           NN: [56.84]            
> ```
> 
> Now this and all other results were more than 52.
> 
> Did this work for your experiment?

Hi Zesty,
I played around with the script, but I still get low T.

degenprime --amplicon:600 --begin:31 --end:653 --min_temp:55 --max_primers:10 trimmed5_l.clust

      Primer Pair #1        Amplicon Size: [658]      Temp Diff: [00.91]
                Forward                               Reverse
       [GGTTCTACATATAACATAATTA]               [TGTCCAAAAGTAAATTTTTT]
           Basic Information                     Basic Information
            Range: [141-162]                      Range: [799-779]
           Length: [22]                          Length: [20]
          Penalty: [99.39]                      Penalty: [92.93]
          Melting Temperature                   Melting Temperature
            Basic: [43.65]                        Basic: [39.48]
               NN: [40.59]                           NN: [41.51]

degenprime --amplicon:800 --begin:42 --end:937 --min_temp:55 --max_primers:10 trimmed4_l.clust

      Primer Pair #1        Amplicon Size: [815]      Temp Diff: [00.85]
                Forward                               Reverse
       [GGTTCTACATATAACATAATTA]               [TCTAAAAATTTTAATTCCGG]
           Basic Information                     Basic Information
            Range: [141-162]                      Range: [956-936]
           Length: [22]                          Length: [20]
          Penalty: [99.39]                      Penalty: [95.33]
          Melting Temperature                   Melting Temperature
            Basic: [43.65]                        Basic: [41.53]
               NN: [40.59]                           NN: [41.44]
               
Could it be caused by a wrong begin/end flag?
Best wishes to both you and Rick,
Mattia

**Comment by raw-lab** [comment] 2024-08-12 12:38
Mattia where you able to get this to work?
Let us know if there was issues? 
Closing for now.

**Closed by raw-lab** 2024-08-12 12:38 UTC

**Comment by forianfinest** [comment] 2024-12-19 11:40
Sorry for answering so late, it has been quite a period.

I reanalyze the alignment; I would suppose there are too few conserved sites for the amplicon I was looking for. I consider this as closed too.
